### ISSUE TITLE
action to auto-build on readthedocs

### ISSUE THREAD

**Issue by superstar54** [beautiful-atoms/beautiful-atoms-docs#17]
Add a GitHub action to update (build) the documentation (readthedocs) when updating the main branch.

@alchem0x2A is this possible?

**Comment by alchem0x2A** [comment]
Not familiar with readthedocs but maybe you want to check https://github.com/dfm/rtds-action?

**Comment by alchem0x2A** [comment]
Oh actually we don't need actions to push changes to readthedocs (can add actions for sphinx build to detect something broken but just optional)

In its tutorial there is a section describing adding webhooks from github --> readthedocs, https://docs.readthedocs.io/en/stable/integrations.html#github maybe you can give a try?

**Comment by superstar54** [comment]
Thanks. I tried, but there is a permission problem, which may be due to the organization's account. I will dig into it more.

**Comment by alchem0x2A** [comment]
@superstar54 I think the issue is solved now? Last direct commit to repo seems already changed in the docs.

**Comment by superstar54** [comment]
Yes, it seems that new commits will trigger new builds in readthedocs.
